[tool.poetry]
name = "dreamcoder-arc"
version = "0.1.0"
description = ""
authors = ["hiroki"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.8.10"
arckit = "0.1.0"
brotlipy = "0.7.0"
cairocffi = "1.6.1"
certifi = "2022.12.7"
cffi = "1.14.3"
chardet = "3.0.4"
charset-normalizer = "3.4.0"
click = "8.1.7"
cryptography = "3.2.1"
cycler = "0.11.0"
dill = "0.3.6"
docker-pycreds = "0.4.0"
drawsvg = "2.4.0"
exceptiongroup = "1.2.2"
fonttools = "4.25.0"
frozendict = "2.4.6"
gitdb = "4.0.11"
GitPython = "3.1.43"
graphviz = "0.20.1"
idna = "2.10"
importlib-metadata = "4.11.3"
iniconfig = "2.0.0"
joblib = "1.1.1"
kiwisolver = "1.4.2"
line-profiler = "4.1.3"
markdown-it-py = "2.2.0"
matplotlib = "3.5.1"
mdurl = "0.1.2"
munkres = "1.1.4"
numpy = "^1.21.0"
packaging = "22.0"
Pillow = "9.0.1"
platformdirs = "4.0.0"
pluggy = "1.0.0"
pox = "0.3.3"
ppft = "1.7.6.7"
protobuf = "3.19.1"
psutil = "6.1.0"
pycairo = "1.23.0"
pycosat = "0.6.3"
pycparser = "2.20"
pygame = "2.6.1"
Pygments = "2.17.2"
pyOpenSSL = "19.1.0"
pyparsing = "3.0.9"
pypng = "0.20220715.0"
PySocks = "1.7.1"
python-dateutil = "2.8.2"
PyYAML = "6.0.1"
pyzmq = "22.3.0"
requests = "2.31.0"
rich = "13.8.1"
scikit-learn = "1.0.2"
scipy = "1.6.2"
sentry-sdk = "2.17.0"
setproctitle = "1.3.3"
setuptools = "^65.0.0"
sexpdata = "1.0.2"
six = "1.15.0"
smmap = "5.0.1"
threadpoolctl = "2.2.0"
tomli = "2.0.1"
toolz = "0.12.0"
tornado = "6.1"
tqdm = "4.51.0"
typing_extensions = "4.7.1"
urllib3 = "2.0.7"
vose = "0.0.1"
wandb = "0.18.5"
wheel = "^0.38.0"
torch = "1.13.1"
[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
